openapi: 3.0.3
info:
  title: School Tracker API project
  version: 1.0.0
  description: App for tracking child activity in educational institution
paths:
  /api/schema/:
    get:
      operationId: schema_retrieve
      description: |-
        OpenApi3 schema for this API. Format can be selected via content negotiation.

        - YAML: application/vnd.oai.openapi
        - JSON: application/vnd.oai.openapi+json
      parameters:
      - in: query
        name: format
        schema:
          type: string
          enum:
          - json
          - yaml
      - in: query
        name: lang
        schema:
          type: string
          enum:
          - af
          - ar
          - ar-dz
          - ast
          - az
          - be
          - bg
          - bn
          - br
          - bs
          - ca
          - cs
          - cy
          - da
          - de
          - dsb
          - el
          - en
          - en-au
          - en-gb
          - eo
          - es
          - es-ar
          - es-co
          - es-mx
          - es-ni
          - es-ve
          - et
          - eu
          - fa
          - fi
          - fr
          - fy
          - ga
          - gd
          - gl
          - he
          - hi
          - hr
          - hsb
          - hu
          - hy
          - ia
          - id
          - ig
          - io
          - is
          - it
          - ja
          - ka
          - kab
          - kk
          - km
          - kn
          - ko
          - ky
          - lb
          - lt
          - lv
          - mk
          - ml
          - mn
          - mr
          - ms
          - my
          - nb
          - ne
          - nl
          - nn
          - os
          - pa
          - pl
          - pt
          - pt-br
          - ro
          - ru
          - sk
          - sl
          - sq
          - sr
          - sr-latn
          - sv
          - sw
          - ta
          - te
          - tg
          - th
          - tk
          - tr
          - tt
          - udm
          - uk
          - ur
          - uz
          - vi
          - zh-hans
          - zh-hant
      tags:
      - schema
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/vnd.oai.openapi:
              schema:
                type: object
                additionalProperties: {}
            application/yaml:
              schema:
                type: object
                additionalProperties: {}
            application/vnd.oai.openapi+json:
              schema:
                type: object
                additionalProperties: {}
            application/json:
              schema:
                type: object
                additionalProperties: {}
          description: ''
  /api/v1/chats/:
    get:
      operationId: v1_chats_list
      tags:
      - v1
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Message'
          description: ''
  /api/v1/chats/{message_id}/:
    get:
      operationId: v1_chats_retrieve
      parameters:
      - in: path
        name: message_id
        schema:
          type: integer
        required: true
      tags:
      - v1
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Message'
          description: ''
  /api/v1/chats/create/:
    post:
      operationId: v1_chats_create_create
      tags:
      - v1
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Message'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Message'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Message'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Message'
          description: ''
  /api/v1/dayplans/:
    get:
      operationId: v1_dayplans_list
      tags:
      - v1
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DayPlan'
          description: ''
    post:
      operationId: v1_dayplans_create
      tags:
      - v1
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DayPlan'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/DayPlan'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/DayPlan'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DayPlan'
          description: ''
  /api/v1/dayplans/child/{id}/{day}/:
    get:
      operationId: v1_dayplans_child_retrieve
      parameters:
      - in: path
        name: day
        schema:
          type: string
        required: true
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - v1
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          description: No response body
  /api/v1/members/child/{id}/:
    get:
      operationId: v1_members_child_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - v1
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Child'
          description: ''
    put:
      operationId: v1_members_child_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - v1
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Child'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Child'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Child'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Child'
          description: ''
    patch:
      operationId: v1_members_child_partial_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - v1
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedChild'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedChild'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedChild'
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Child'
          description: ''
  /api/v1/members/children/:
    get:
      operationId: v1_members_children_list
      tags:
      - v1
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Child'
          description: ''
    post:
      operationId: v1_members_children_create
      tags:
      - v1
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Child'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Child'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Child'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Child'
          description: ''
  /api/v1/members/group/:
    get:
      operationId: v1_members_group_list
      tags:
      - v1
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Group'
          description: ''
    post:
      operationId: v1_members_group_create
      tags:
      - v1
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Group'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Group'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Group'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Group'
          description: ''
  /api/v1/members/group/{id}/:
    get:
      operationId: v1_members_group_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - v1
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Group'
          description: ''
  /api/v1/members/parent/:
    get:
      operationId: v1_members_parent_list
      tags:
      - v1
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Parent'
          description: ''
    post:
      operationId: v1_members_parent_create
      tags:
      - v1
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Parent'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Parent'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Parent'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Parent'
          description: ''
  /api/v1/members/parent/{id}/:
    get:
      operationId: v1_members_parent_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - v1
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Parent'
          description: ''
    put:
      operationId: v1_members_parent_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - v1
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Parent'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Parent'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Parent'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Parent'
          description: ''
    patch:
      operationId: v1_members_parent_partial_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - v1
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedParent'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedParent'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedParent'
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Parent'
          description: ''
components:
  schemas:
    BehaviourEnum:
      enum:
      - OK
      - NT
      - ND
      type: string
      description: |-
        * `OK` - Everything ok
        * `NT` - We need to talk
        * `ND` - Not defined
    Child:
      type: object
      properties:
        full_name:
          type: string
          maxLength: 100
        age:
          type: string
          readOnly: true
        parent:
          type: integer
      required:
      - age
      - full_name
      - parent
    DayPlan:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        day:
          type: string
          format: date
          readOnly: true
        meals_at_school:
          $ref: '#/components/schemas/MealsAtSchoolEnum'
        behaviour:
          $ref: '#/components/schemas/BehaviourEnum'
        summary:
          type: string
          nullable: true
        child:
          type: integer
      required:
      - child
      - day
      - id
    Group:
      type: object
      properties:
        group_name:
          type: string
          maxLength: 50
        members:
          type: array
          items:
            type: integer
        teacher:
          type: integer
      required:
      - group_name
      - members
      - teacher
    MealsAtSchoolEnum:
      enum:
      - FL
      - HF
      - FW
      - NM
      type: string
      description: |-
        * `FL` - Fully eaten
        * `HF` - Halfy eaten
        * `FW` - Poorly eaten
        * `NM` - Not marked
    Message:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        sender:
          type: integer
          readOnly: true
        child:
          type: integer
          nullable: true
        message_text:
          type: string
          maxLength: 1000
        timestamp:
          type: string
          format: date-time
          readOnly: true
      required:
      - id
      - message_text
      - sender
      - timestamp
    Parent:
      type: object
      properties:
        user:
          type: integer
        child:
          type: array
          items:
            type: integer
      required:
      - child
      - user
    PatchedChild:
      type: object
      properties:
        full_name:
          type: string
          maxLength: 100
        age:
          type: string
          readOnly: true
        parent:
          type: integer
    PatchedParent:
      type: object
      properties:
        user:
          type: integer
        child:
          type: array
          items:
            type: integer
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
