# Generated by Django 5.0.6 on 2024-05-20 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('TH', 'Teacher'), ('PR', 'Parent'), ('US', 'Unset')], default=['US'], max_length=2),
        ),
    ]
