# Generated by Django 4.1.7 on 2023-05-25 11:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chats", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={"ordering": ("-timestamp",)},
        ),
    ]
