# Generated by Django 4.1.7 on 2023-05-10 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("members", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="DayPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.DateField(auto_now=True)),
                (
                    "meals_at_school",
                    models.CharField(
                        choices=[
                            ("FL", "Fully eaten"),
                            ("HF", "Halfy eaten"),
                            ("FW", "Poorly eaten"),
                            ("NM", "Not marked"),
                        ],
                        default="NM",
                        max_length=2,
                    ),
                ),
                (
                    "behaviour",
                    models.CharField(
                        choices=[
                            ("OK", "Everything ok"),
                            ("NT", "We need to talk"),
                            ("ND", "Not defined"),
                        ],
                        default="ND",
                        max_length=2,
                    ),
                ),
                ("summary", models.TextField(blank=True, null=True)),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="members.child"
                    ),
                ),
            ],
            options={
                "verbose_name": "Dayplan",
                "verbose_name_plural": "Dayplans",
            },
        ),
    ]
